server {
	#listen		80;
	listen		443 ssl;
    ssl_certificate	/etc/nginx/ssl/transcendence.pem;
    ssl_certificate_key	/etc/nginx/ssl/transcendence.key;
	server_name	transcendence.fr;

	location / {
		proxy_pass http://app:8000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_redirect off;
	}

	location /static/ {
		alias /static/;
	}
}
