ssl_session_cache   shared:SSL:10m;
ssl_session_timeout 10m;

upstream frontend {
    server nextjs:3000;
}

upstream service_1 {
    server app:8000;
}

upstream pong_backend {
	server pong_backend:8000;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    listen				80;
    server_name			localhost;
	return 301 https://${DOMAIN_NAME}:443$request_uri;
}

server {
	listen		443 ssl;
	server_name ${DOMAIN_NAME};
    ssl_certificate	/etc/nginx/ssl/transcendence.pem;
    ssl_certificate_key	/etc/nginx/ssl/transcendence.key;
    ssl_protocols   TLSv1.2 TLSv1.3;
    ssl_ciphers		HIGH:!aNULL:!MD5;

	location / {
		proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_redirect off;
	}

	location /api {
		proxy_pass http://service_1;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_redirect off;
	}

	location /static/ {
		alias /static/;
	}

	 location /ws/ {
        proxy_pass http://pong_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
