    services:
        nginx:
          depends_on:
              - nextjs
          build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
          ports:
            - "443:443/tcp"
          image: nginx:1.27.1
          container_name: nginx
          env_file: ./env/.env_nginx
          init: true
          restart: always
          networks:
            network:
              ipv4_address: 172.18.0.2
          hostname: nginx
          volumes:
              - "static_service_app:/static/api"
              - "static_service_chat:/static/chat"

        nextjs:
          depends_on:
              - service_app_django
              - service_chat_django
          build:
            context: ./requirements/nextjs
            dockerfile: Dockerfile
          image: nextjs
          container_name: nextjs
          init: true
          restart: always
          networks:
            network:
              ipv4_address: 172.18.0.3
          hostname: nextjs
          volumes:
              - "nextjs:/transcendence"

        service_app_django:
          depends_on:
              - service_app_postgresql
          build:
            context: ./requirements/service_app/django
            dockerfile: Dockerfile
          image: python:3.13.0rc1
          container_name: service_app_django
          env_file:
            - ./env/.env_nginx
            - ./env/.env_service_app
          init: true
          restart: always
          networks:
            network:
              ipv4_address: 172.18.0.4
          hostname: service_app_django
          volumes:
              - "service_app_django:/django_web_app"
              - "static_service_app:/static"

        service_app_postgresql:
          build:
            context: ./requirements/service_app/postgresql
            dockerfile: Dockerfile
          image: postgres:16.4
          container_name: service_app_postgresql
          init: true
          restart: always
          networks:
            network:
              ipv4_address: 172.18.0.5
          hostname: service_app_postgresql
          volumes:
              - "service_app_postgresql:/var/lib/postgresql/data"

        service_chat_django:
          depends_on:
              - service_chat_postgresql
          build:
            context: ./requirements/service_chat/django
            dockerfile: Dockerfile
          image: python:3.13.0rc1_1
          container_name: service_chat_django
          env_file:
            - ./env/.env_nginx
            - ./env/.env_service_chat
          init: true
          restart: always
          networks:
            network:
              ipv4_address: 172.18.0.6
          hostname: service_chat_django
          volumes:
              - "service_chat_django:/django_web_chat"
              - "static_service_chat:/static"

        service_chat_postgresql:
          build:
            context: ./requirements/service_chat/postgresql
            dockerfile: Dockerfile
          image: postgres:16.4_1
          container_name: service_chat_postgresql
          init: true
          restart: always
          networks:
            network:
              ipv4_address: 172.18.0.7
          hostname: service_chat_postgresql
          volumes:
              - "service_chat_postgresql:/var/lib/postgresql/data"

                #        smart_contract:
                #          depends_on:
                #              - postgresql
                #          build:
                #            context: ./requirements/smart_contract
                #            dockerfile: Dockerfile
                #          image: solidity:10.11.6
                #          container_name: smart_contract
                #          env_file: .env
                #          init: true
                #          restart: always
                #          hostname: smart_contract
                #          volumes:
                #              - "smart_contract:/projects"

                #    volumes:
                #      smart_contract:
                #        driver: local
                #        driver_opts:
                #          type: 'none'
                #          o: 'bind'
                #          device: "../volume/smart_contract"

    networks:
      network:
        driver: bridge
        ipam:
          config:
            - subnet: 172.18.0.0/24

    volumes:
      nextjs:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/nextjs"
      static_service_app:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/static/static_service_app"
      service_app_django:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/service_app/django"
      service_app_postgresql:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/service_app/postgresql"
      static_service_chat:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/static/static_service_chat"
      service_chat_django:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/service_chat/django"
      service_chat_postgresql:
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: "../volume/service_chat/postgresql"
