services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - front-data:/app
      - /app/.next
      - /app/node_modules

  backend:
    build:
      context: ./Backend
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=transcendence
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - back-data:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=transcendence
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./Volume/postgresql"
  front-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./Frontend"
  back-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "./Backend"