# Generated by Django 5.1.3 on 2024-11-19 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('result', models.CharField(choices=[('Win', 'Win'), ('Lose', 'Lose')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=100)),
                ('tournament_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.AddField(
            model_name='match',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='user.user'),
        ),
    ]
