# Generated by Django 5.1.4 on 2025-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
