# Generated by Django 5.1.7 on 2025-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='is_tournament',
            field=models.BooleanField(default=True),
        ),
    ]
