# syntax=docker/dockerfile:1
# escape=\

FROM nginx@sha256:0c57fe90551cfd8b7d4d05763c5018607b296cb01f7e0ff44b7d047353ed8cc0

RUN apk update && apk upgrade && apk add vim

EXPOSE 443

CMD ["sleep", "infinity"]
